FROM python:3.7

ENV COMMIT_HASH=50388c55428d742d73d9733278f04173585de80d

WORKDIR /app

RUN git clone https://github.com/apache/skywalking-python.git $(pwd)

RUN git reset --hard ${COMMIT_HASH} && git submodule update --init

RUN make setup install

ADD ./provider.py /provider.py
