FROM node:10.23 AS builder

WORKDIR /skywalking-client-test

ADD . /skywalking-client-test

RUN cp test/index.js src/index.js \
    && npm install \
    && npm run build

FROM nginx:1.19

COPY --from=builder /skywalking-client-test/dist/* /etc/nginx/html/
COPY test/docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
