name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
      - name: Create service with docker compose
        run: |
          docker compose -f test/all-in-one.yaml up -d
          docker ps
          sleep 60
          docker compose -f test/all-in-one.yaml logs test-ui
      - name: Clean Up
        if: ${{ always() }}
        run: docker compose -f test/all-in-one.yaml down